// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaRnpj9JitoIJeVveSMnovFqkKVRhZOYc',
    appId: '1:54454235211:web:5c7bf18163c6da2badddce',
    messagingSenderId: '54454235211',
    projectId: 'news-wave-eca83',
    authDomain: 'news-wave-eca83.firebaseapp.com',
    storageBucket: 'news-wave-eca83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7htWZc2dGYeOXI3HyGjG45fuq8khlI0',
    appId: '1:54454235211:android:1578e762a20f8bbcadddce',
    messagingSenderId: '54454235211',
    projectId: 'news-wave-eca83',
    storageBucket: 'news-wave-eca83.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5Yi_9_etDw83pd69W9x0WxGNnF3CiPo',
    appId: '1:54454235211:ios:2fa9afc4de033d17adddce',
    messagingSenderId: '54454235211',
    projectId: 'news-wave-eca83',
    storageBucket: 'news-wave-eca83.appspot.com',
    iosClientId: '54454235211-ui14f1lnv1oe2cpggpm5isgrh3qhlhvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaRnpj9JitoIJeVveSMnovFqkKVRhZOYc',
    appId: '1:54454235211:web:22261d387a116c18adddce',
    messagingSenderId: '54454235211',
    projectId: 'news-wave-eca83',
    authDomain: 'news-wave-eca83.firebaseapp.com',
    storageBucket: 'news-wave-eca83.appspot.com',
  );
}
